version : '3'
services:
  mysql:
    image: mysql:lts
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql"